language: node_js
services: mongodb
node_js:
  - "0.8"
  - "0.10"
install:
  - npm update npm -g
  - npm install -g grunt-cli
  - npm install
script:
  - cp config.json-dist config.json
  - grunt test